// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWP391_M2_BL5_G4_SP25.Models;

#nullable disable

namespace SWP391_M2_BL5_G4_SP25.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.ClientProfile", b =>
                {
                    b.Property<int>("ClientProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("ClientProfileID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<int>("ClientProfileID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("CompanyID");

                    b.HasIndex("ClientProfileID")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.CompanyReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("ReviewID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID");

                    b.ToTable("CompanyReviews");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("JobID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("JobCategoryID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobApplication", b =>
                {
                    b.Property<int>("JobApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationID"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("JobApplicationID");

                    b.HasIndex("JobID");

                    b.HasIndex("UserID");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("JobCategoryID");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            JobCategoryID = 1,
                            CategoryName = "Software Development",
                            Description = "Jobs related to software engineering and development",
                            isDelete = false
                        },
                        new
                        {
                            JobCategoryID = 2,
                            CategoryName = "Marketing",
                            Description = "Jobs in marketing and advertising",
                            isDelete = false
                        },
                        new
                        {
                            JobCategoryID = 3,
                            CategoryName = "Finance",
                            Description = "Jobs in finance and accounting",
                            isDelete = false
                        },
                        new
                        {
                            JobCategoryID = 4,
                            CategoryName = "Human Resources",
                            Description = "Jobs in HR and recruitment",
                            isDelete = false
                        },
                        new
                        {
                            JobCategoryID = 5,
                            CategoryName = "Design",
                            Description = "Jobs in graphic and UI/UX design",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobSeekerProfile", b =>
                {
                    b.Property<int>("JobSeekerProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSeekerProfileID"));

                    b.Property<string>("CV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("JobSeekerProfileID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("JobSeekerProfiles");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("NotificationID");

                    b.HasIndex("JobID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "User looking for job opportunities",
                            RoleName = "JobSeeker",
                            isDelete = false
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "User representing a company posting jobs",
                            RoleName = "Employer",
                            isDelete = false
                        },
                        new
                        {
                            RoleID = 3,
                            Description = "System administrator",
                            RoleName = "Admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Skills", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<int?>("JobSeekerProfileID")
                        .HasColumnType("int");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("SkillID");

                    b.HasIndex("JobID");

                    b.HasIndex("JobSeekerProfileID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.ClientProfile", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("SWP391_M2_BL5_G4_SP25.Models.ClientProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Company", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.ClientProfile", "ClientProfile")
                        .WithOne("Company")
                        .HasForeignKey("SWP391_M2_BL5_G4_SP25.Models.Company", "ClientProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientProfile");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.CompanyReview", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Company", "Company")
                        .WithMany("CompanyReviews")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.User", "User")
                        .WithMany("CompanyReviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Job", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.JobCategory", "JobCategory")
                        .WithMany("Jobs")
                        .HasForeignKey("JobCategoryID");

                    b.Navigation("Company");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobApplication", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.User", "User")
                        .WithMany("JobApplications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobSeekerProfile", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.User", "User")
                        .WithOne("JobSeekerProfile")
                        .HasForeignKey("SWP391_M2_BL5_G4_SP25.Models.JobSeekerProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Notification", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Skills", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.JobSeekerProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("JobSeekerProfileID");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.User", b =>
                {
                    b.HasOne("SWP391_M2_BL5_G4_SP25.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.ClientProfile", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Company", b =>
                {
                    b.Navigation("CompanyReviews");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Job", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.JobSeekerProfile", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWP391_M2_BL5_G4_SP25.Models.User", b =>
                {
                    b.Navigation("ClientProfile")
                        .IsRequired();

                    b.Navigation("CompanyReviews");

                    b.Navigation("JobApplications");

                    b.Navigation("JobSeekerProfile")
                        .IsRequired();

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
